name: Update README

on:
  schedule:
    - cron: '0 * * * *'  # Läuft jede Stunde
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README
        run: |
          curl -o- -L https://github-profile-readme-generator.com/LukiDev17 | bash
      - name: Commit changes
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git commit -m "Updated README"
          git push
